import { useEffect, useState } from 'react';
import { Link } from 'wouter';
import { ArrowUpRight, LockKeyhole, Sparkles, Check, ShieldCheck } from 'lucide-react';
import { AppNav } from '@/components/shared/app-nav';
import { PublicFooter } from '@/components/shared/public-shell';

export default function ProPage() {
  const [plan, setPlan] = useState<'monthly' | 'annual'>('annual');
  const [requested, setRequested] = useState(false);
  useEffect(() => {
    document.title = "Career Reality Pro | CareerReality";
  }, []);
  return (
    <div className="grain min-h-[100dvh]">
      <AppNav />
      <main className="mx-auto max-w-[1240px] px-5 py-16 sm:px-8 sm:py-24">
        <div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:gap-20">
          <div className="animate-enter"><span className="font-data text-[10px] uppercase tracking-[.2em] text-primary">Career Reality Pro</span><h1 className="mt-5 max-w-[690px] font-display text-[62px] leading-[.9] tracking-[-.05em] sm:text-[91px]">The context<br /><span className="text-primary">behind the move.</span></h1><p className="mt-7 max-w-[530px] text-[15px] leading-[1.7] text-muted-foreground">For decisions where a headline is not enough. Pro brings deeper company intelligence, role-level salary reads, and a private decision workspace together.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#plans" className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-[12px] font-bold text-primary-foreground" data-testid="link-pro-plans">See membership <ArrowUpRight size={15} /></a><Link href="/" className="inline-flex items-center gap-2 rounded-full border border-border px-5 py-3 text-[12px] font-bold" data-testid="link-back-home">Back to the desk</Link></div></div>
          <div className="paper-grid rounded-[22px] border border-border p-4 sm:p-6 animate-enter-delay"><div className="rounded-[16px] bg-[#263138] p-5 text-[#f2eadc] sm:p-7"><div className="flex items-center justify-between"><span className="font-data text-[10px] uppercase tracking-[.18em] text-[#83c9b4]">Private workspace / live</span><LockKeyhole size={15} className="text-[#e5b755]" /></div><p className="mt-10 font-display text-4xl leading-[.95]">Should I take<br />the offer?</p><div className="mt-8 space-y-3">{['Offer is +14.2% above market', 'Company stability: watch', 'Resignation cost: 3.5 months'].map((item, index) => <div key={item} className="flex items-center justify-between border-t border-[#46545a] pt-3 text-[11px]"><span className="text-[#bac7c0]">{item}</span><span className={`font-data ${index === 1 ? 'text-[#e5b755]' : 'text-[#83c9b4]'}`}>{index === 1 ? '64 / 100' : index === 2 ? '₹4.2L' : 'strong'}</span></div>)}</div><div className="mt-8 rounded-lg bg-[#3d4a51] p-3 text-[10px] leading-[1.5] text-[#c6d1ca]"><Sparkles size={13} className="mb-1 text-[#e5b755]" /> Your next question: What would make this move worth the risk?</div></div></div>
        </div>
        <section id="plans" className="mt-24 border-t border-border pt-16"><div className="flex flex-wrap items-end justify-between gap-5"><div><span className="font-data text-[10px] uppercase tracking-[.2em] text-primary">A membership for the considered</span><h2 className="mt-3 font-display text-[45px] leading-[.95] tracking-[-.04em] sm:text-[60px]">More signal.<br /><span className="text-muted-foreground">Less second-guessing.</span></h2></div><div className="flex rounded-full border border-border p-1 text-[10px] font-bold"><button onClick={() => setPlan('monthly')} className={`rounded-full px-3 py-2 ${plan === 'monthly' ? 'bg-muted' : 'text-muted-foreground'}`} data-testid="button-plan-monthly">Monthly</button><button onClick={() => setPlan('annual')} className={`rounded-full px-3 py-2 ${plan === 'annual' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`} data-testid="button-plan-annual">Annual · save 20%</button></div></div>
          <div className="mt-10 grid gap-3 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[18px] border border-primary bg-primary p-6 text-primary-foreground sm:p-8"><div className="flex items-start justify-between"><div><p className="font-data text-[10px] uppercase tracking-[.18em] text-[#a9dbca]">Career Reality Pro</p><p className="mt-3 font-display text-4xl">For the move<br />you cannot unmake.</p></div><span className="rounded-full bg-[#e5b755] px-2.5 py-1 font-data text-[9px] font-bold text-foreground">RECOMMENDED</span></div><div className="mt-9 flex items-end gap-2"><span className="font-data text-4xl">₹{plan === 'annual' ? '2,400' : '249'}</span><span className="pb-1 text-[11px] text-[#a9dbca]">/{plan === 'annual' ? 'year' : 'month'}</span></div><div className="mt-6 space-y-3 border-t border-[#4b8b7a] pt-5">{['Full company intelligence and layoff radar', 'Private decision workspace with saved reads', 'Early access to salary and AI pulse reports', 'Ask a researcher — one question each month'].map((item) => <p key={item} className="flex items-center gap-2 text-[12px]"><Check size={14} className="text-[#e5b755]" /> {item}</p>)}</div><button onClick={() => setRequested(true)} className="mt-8 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#e5b755] text-[12px] font-bold text-foreground" data-testid="button-join-pro">{requested ? <><Check size={15} /> Request received</> : <>Start with Pro <ArrowUpRight size={15} /></>}</button></div><div className="rounded-[18px] border border-border bg-card p-6 sm:p-8"><p className="font-data text-[10px] uppercase tracking-[.18em] text-muted-foreground">What does “signal” mean?</p><p className="mt-8 font-display text-3xl leading-[1]">A number without<br />its context is just noise.</p><p className="mt-5 text-[13px] leading-[1.7] text-muted-foreground">Every Pro read carries its source, date, confidence, and the decision it can actually inform. We would rather show you an honest “not enough data” than a confident guess.</p><div className="mt-8 border-t border-border pt-5"><p className="flex items-center gap-2 text-[11px] font-bold"><ShieldCheck size={15} className="text-primary" /> No selling your data. Ever.</p><p className="mt-2 text-[10px] leading-[1.5] text-muted-foreground">Your private workspace stays private. Contributions are aggregated and anonymised.</p></div></div></div>
        </section>
      </main>
      <PublicFooter />
    </div>
  );
}